"""
Seed script: ~70 Chinese universities with English programs for CIS students.
Run: python -m seeds.universities
"""
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.database import SessionLocal
from app.models.university import University, Major, Scholarship, Deadline
from datetime import date

UNIVERSITIES = [
    # ── C9 League ──────────────────────────────────────────────────────────
    {
        "slug": "pku", "name": "Peking University", "name_cn": "北京大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 5,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "partial",
        "qs_rank": 14, "the_rank": 12, "intl_pct": 12,
        "ielts_min": 6.5, "app_fee_usd": 0, "tuition_cny_yr": 32000,
        "portal_status": "OPEN", "tier": "REACH",
        "url_info": "https://www.pku.edu.cn",
        "url_portal": "https://admission.pku.edu.cn",
        "coordinates": {"lat": 39.9997, "lng": 116.3104},
        "notes_public": "One of China's top 2. Very selective for internationals. Strong in humanities, sciences.",
    },
    {
        "slug": "thu", "name": "Tsinghua University", "name_cn": "清华大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 5,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "partial",
        "qs_rank": 25, "the_rank": 16, "intl_pct": 10,
        "ielts_min": 6.5, "app_fee_usd": 0, "tuition_cny_yr": 34000,
        "portal_status": "OPEN", "tier": "REACH",
        "url_info": "https://www.tsinghua.edu.cn",
        "url_portal": "https://www.tsinghua.edu.cn/en/Admissions",
        "coordinates": {"lat": 40.0028, "lng": 116.3258},
        "notes_public": "China's MIT. Top engineering, CS, architecture. Very competitive.",
    },
    {
        "slug": "sjtu", "name": "Shanghai Jiao Tong University", "name_cn": "上海交通大学",
        "city": "Shanghai", "province": "Shanghai", "prestige_stars": 5,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 47, "the_rank": 49, "intl_pct": 12,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 40000,
        "portal_status": "OPEN", "tier": "REACH",
        "url_info": "https://en.sjtu.edu.cn",
        "url_portal": "https://admission.sjtu.edu.cn",
        "coordinates": {"lat": 31.2002, "lng": 121.4266},
        "notes_public": "Strong in engineering, medicine, finance. Shanghai location is a big plus.",
    },
    {
        "slug": "fudan", "name": "Fudan University", "name_cn": "复旦大学",
        "city": "Shanghai", "province": "Shanghai", "prestige_stars": 5,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "partial",
        "qs_rank": 50, "the_rank": 55, "intl_pct": 15,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 36000,
        "portal_status": "OPEN", "tier": "REACH",
        "url_info": "https://www.fudan.edu.cn",
        "url_portal": "https://admission.fudan.edu.cn",
        "coordinates": {"lat": 31.2981, "lng": 121.5039},
        "notes_public": "Strong in liberal arts, medicine, international studies.",
    },
    {
        "slug": "zju", "name": "Zhejiang University", "name_cn": "浙江大学",
        "city": "Hangzhou", "province": "Zhejiang", "prestige_stars": 5,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 44, "the_rank": 67, "intl_pct": 9,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 28000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.zju.edu.cn/english",
        "url_portal": "https://zjuintl.zju.edu.cn",
        "coordinates": {"lat": 30.2602, "lng": 120.1222},
        "notes_public": "Beautiful campus in Hangzhou near Alibaba HQ. Strong tech programs.",
    },
    {
        "slug": "nju", "name": "Nanjing University", "name_cn": "南京大学",
        "city": "Nanjing", "province": "Jiangsu", "prestige_stars": 5,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "partial",
        "qs_rank": 133, "the_rank": 189, "intl_pct": 8,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 26000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.nju.edu.cn/en",
        "url_portal": "https://international.nju.edu.cn",
        "coordinates": {"lat": 32.0572, "lng": 118.7967},
        "notes_public": "Strong in chemistry, astronomy, earth sciences.",
    },
    {
        "slug": "ustc", "name": "University of Science and Technology of China", "name_cn": "中国科学技术大学",
        "city": "Hefei", "province": "Anhui", "prestige_stars": 5,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "partial",
        "qs_rank": 93, "the_rank": 87, "intl_pct": 4,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 25000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://en.ustc.edu.cn",
        "url_portal": "https://iso.ustc.edu.cn",
        "coordinates": {"lat": 31.8289, "lng": 117.2491},
        "notes_public": "China's Caltech. Elite science/tech. Few English UG programs.",
    },
    {
        "slug": "whu", "name": "Wuhan University", "name_cn": "武汉大学",
        "city": "Wuhan", "province": "Hubei", "prestige_stars": 5,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 201, "the_rank": 251, "intl_pct": 8,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 24000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://en.whu.edu.cn",
        "url_portal": "https://admission.whu.edu.cn",
        "coordinates": {"lat": 30.5389, "lng": 114.3644},
        "notes_public": "Cherry blossom university. Strong in remote sensing, law, economics.",
    },
    {
        "slug": "hit", "name": "Harbin Institute of Technology", "name_cn": "哈尔滨工业大学",
        "city": "Harbin", "province": "Heilongjiang", "prestige_stars": 5,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 236, "the_rank": 301, "intl_pct": 10,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 25000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://en.hit.edu.cn",
        "url_portal": "https://admission.hit.edu.cn",
        "coordinates": {"lat": 45.7279, "lng": 126.6253},
        "notes_public": "China's top aerospace/defense engineering. Close to Russia border.",
    },
    # ── 985 Universities ──────────────────────────────────────────────────
    {
        "slug": "tongji", "name": "Tongji University", "name_cn": "同济大学",
        "city": "Shanghai", "province": "Shanghai", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 227, "the_rank": 351, "intl_pct": 16,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 32000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://en.tongji.edu.cn",
        "url_portal": "https://admission.tongji.edu.cn",
        "coordinates": {"lat": 31.2804, "lng": 121.4991},
        "notes_public": "Top for architecture, urban planning, civil engineering. German ties.",
    },
    {
        "slug": "buaa", "name": "Beihang University", "name_cn": "北京航空航天大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 350, "the_rank": 401, "intl_pct": 8,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 28000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://ev.buaa.edu.cn",
        "url_portal": "https://sie.buaa.edu.cn",
        "coordinates": {"lat": 40.0046, "lng": 116.3444},
        "notes_public": "Aerospace, aviation, astronautics. Top defense university.",
    },
    {
        "slug": "bit", "name": "Beijing Institute of Technology", "name_cn": "北京理工大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 400, "the_rank": 401, "intl_pct": 9,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 27000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://english.bit.edu.cn",
        "url_portal": "https://sie.bit.edu.cn",
        "coordinates": {"lat": 39.9567, "lng": 116.3189},
        "notes_public": "Engineering focus. Great for robotics, automation, material science.",
    },
    {
        "slug": "hust", "name": "Huazhong University of Science and Technology", "name_cn": "华中科技大学",
        "city": "Wuhan", "province": "Hubei", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 275, "the_rank": 251, "intl_pct": 8,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://english.hust.edu.cn",
        "url_portal": "https://sie.hust.edu.cn",
        "coordinates": {"lat": 30.5094, "lng": 114.4142},
        "notes_public": "Strong in EE, optics, medicine. Large campus.",
    },
    {
        "slug": "sdu", "name": "Shandong University", "name_cn": "山东大学",
        "city": "Jinan", "province": "Shandong", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 451, "the_rank": 501, "intl_pct": 7,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 20000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.en.sdu.edu.cn",
        "url_portal": "https://iso.sdu.edu.cn",
        "coordinates": {"lat": 36.6841, "lng": 117.0568},
        "notes_public": "Comprehensive university, strong humanities, history.",
    },
    {
        "slug": "xjtu", "name": "Xi'an Jiaotong University", "name_cn": "西安交通大学",
        "city": "Xi'an", "province": "Shaanxi", "prestige_stars": 4,
        "league": "C9", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 302, "the_rank": 301, "intl_pct": 7,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.xjtu.edu.cn/en",
        "url_portal": "https://sie.xjtu.edu.cn",
        "coordinates": {"lat": 34.2511, "lng": 108.9856},
        "notes_public": "Strong in energy engineering, medicine, management. Silk Road location.",
    },
    {
        "slug": "sysu", "name": "Sun Yat-sen University", "name_cn": "中山大学",
        "city": "Guangzhou", "province": "Guangdong", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 275, "the_rank": 201, "intl_pct": 6,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 26000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.sysu.edu.cn/en",
        "url_portal": "https://iso.sysu.edu.cn",
        "coordinates": {"lat": 23.0985, "lng": 113.3003},
        "notes_public": "Guangdong's top uni. Close to HK. Strong in life sciences, medicine.",
    },
    {
        "slug": "seu", "name": "Southeast University", "name_cn": "东南大学",
        "city": "Nanjing", "province": "Jiangsu", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 471, "the_rank": 401, "intl_pct": 8,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 24000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.seu.edu.cn/English",
        "url_portal": "https://isa.seu.edu.cn",
        "coordinates": {"lat": 32.0576, "lng": 118.7966},
        "notes_public": "Strong in architecture, electronic info, transportation.",
    },
    {
        "slug": "dlut", "name": "Dalian University of Technology", "name_cn": "大连理工大学",
        "city": "Dalian", "province": "Liaoning", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 501, "the_rank": 401, "intl_pct": 9,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 24000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://en.dlut.edu.cn",
        "url_portal": "https://sie.dlut.edu.cn",
        "coordinates": {"lat": 38.8711, "lng": 121.5288},
        "notes_public": "Great coastal city. Strong engineering, shipbuilding.",
    },
    {
        "slug": "csu", "name": "Central South University", "name_cn": "中南大学",
        "city": "Changsha", "province": "Hunan", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 451, "the_rank": 301, "intl_pct": 7,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://en.csu.edu.cn",
        "url_portal": "https://iso.csu.edu.cn",
        "coordinates": {"lat": 28.1549, "lng": 112.9444},
        "notes_public": "World #1 in metallurgy & mining. Strong medical school.",
    },
    # ── HK-Affiliated ──────────────────────────────────────────────────────
    {
        "slug": "hkust-gz", "name": "HKUST (Guangzhou)", "name_cn": "香港科技大学（广州）",
        "city": "Guangzhou", "province": "Guangdong", "prestige_stars": 5,
        "league": "HK-Affiliated", "diploma_type": "HK", "english_ug": "yes",
        "qs_rank": 40, "the_rank": 58, "intl_pct": 30,
        "ielts_min": 6.5, "app_fee_usd": 0, "tuition_cny_yr": 120000,
        "portal_status": "OPEN", "tier": "REACH",
        "url_info": "https://hkust-gz.edu.cn",
        "url_portal": "https://hkust-gz.edu.cn/admissions",
        "coordinates": {"lat": 23.1840, "lng": 113.5080},
        "notes_public": "New campus. HK degree. Fully English. Advanced hubs model.",
    },
    {
        "slug": "cuhk-sz", "name": "CUHK-Shenzhen", "name_cn": "香港中文大学（深圳）",
        "city": "Shenzhen", "province": "Guangdong", "prestige_stars": 5,
        "league": "HK-Affiliated", "diploma_type": "HK", "english_ug": "yes",
        "qs_rank": 54, "the_rank": 89, "intl_pct": 18,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 85000,
        "portal_status": "OPEN", "tier": "REACH",
        "url_info": "https://www.cuhk.edu.cn/en",
        "url_portal": "https://admission.cuhk.edu.cn",
        "coordinates": {"lat": 22.6839, "lng": 114.2124},
        "notes_public": "HK degree in Shenzhen. Top for CS, Finance, Economics.",
    },
    {
        "slug": "hku-sz", "name": "HKU-Shenzhen", "name_cn": "港大深圳",
        "city": "Shenzhen", "province": "Guangdong", "prestige_stars": 5,
        "league": "HK-Affiliated", "diploma_type": "HK", "english_ug": "yes",
        "qs_rank": 26, "the_rank": 35, "intl_pct": 35,
        "ielts_min": 6.5, "app_fee_usd": 0, "tuition_cny_yr": 130000,
        "portal_status": "OPEN", "tier": "REACH",
        "url_info": "https://www.hkushenzhencollege.hku.hk",
        "url_portal": "https://aal.hku.hk/admissions",
        "coordinates": {"lat": 22.5391, "lng": 114.0579},
        "notes_public": "HKU brand in mainland China. Very international cohort.",
    },
    # ── US-Affiliated ──────────────────────────────────────────────────────
    {
        "slug": "nyu-shanghai", "name": "NYU Shanghai", "name_cn": "纽约大学上海",
        "city": "Shanghai", "province": "Shanghai", "prestige_stars": 5,
        "league": "US-Affiliated", "diploma_type": "US", "english_ug": "yes",
        "qs_rank": 58, "the_rank": 81, "intl_pct": 50,
        "ielts_min": 6.5, "app_fee_usd": 65, "tuition_cny_yr": 248000,
        "portal_status": "OPEN", "tier": "REACH",
        "url_info": "https://shanghai.nyu.edu",
        "url_portal": "https://shanghai.nyu.edu/admissions",
        "coordinates": {"lat": 31.2226, "lng": 121.4826},
        "notes_public": "NYU degree. International environment. Liberal arts + tech.",
    },
    {
        "slug": "duke-kunshan", "name": "Duke Kunshan University", "name_cn": "昆山杜克大学",
        "city": "Kunshan", "province": "Jiangsu", "prestige_stars": 5,
        "league": "US-Affiliated", "diploma_type": "US", "english_ug": "yes",
        "qs_rank": 130, "the_rank": 201, "intl_pct": 45,
        "ielts_min": 6.5, "app_fee_usd": 75, "tuition_cny_yr": 230000,
        "portal_status": "OPEN", "tier": "REACH",
        "url_info": "https://www.dukekunshan.edu.cn",
        "url_portal": "https://www.dukekunshan.edu.cn/admissions",
        "coordinates": {"lat": 31.3804, "lng": 120.9640},
        "notes_public": "Duke degree. Small cohort. Near Suzhou/Shanghai.",
    },
    {
        "slug": "wenzhou-kean", "name": "Wenzhou-Kean University", "name_cn": "温州肯恩大学",
        "city": "Wenzhou", "province": "Zhejiang", "prestige_stars": 3,
        "league": "US-Affiliated", "diploma_type": "US", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 20,
        "ielts_min": 5.5, "app_fee_usd": 50, "tuition_cny_yr": 80000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.wku.edu.cn",
        "url_portal": "https://www.wku.edu.cn/admissions",
        "coordinates": {"lat": 27.9939, "lng": 120.6999},
        "notes_public": "Kean University degree. More accessible US diploma pathway.",
    },
    # ── UK-Affiliated ──────────────────────────────────────────────────────
    {
        "slug": "xjtlu", "name": "Xi'an Jiaotong-Liverpool University", "name_cn": "西交利物浦大学",
        "city": "Suzhou", "province": "Jiangsu", "prestige_stars": 4,
        "league": "UK-Affiliated", "diploma_type": "UK", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 25,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 80000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.xjtlu.edu.cn/en",
        "url_portal": "https://www.xjtlu.edu.cn/en/admissions",
        "coordinates": {"lat": 31.3041, "lng": 120.5951},
        "notes_public": "Liverpool degree. Option to transfer to Liverpool in UK year 2/3.",
    },
    {
        "slug": "unnc", "name": "University of Nottingham Ningbo China", "name_cn": "宁波诺丁汉大学",
        "city": "Ningbo", "province": "Zhejiang", "prestige_stars": 4,
        "league": "UK-Affiliated", "diploma_type": "UK", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 20,
        "ielts_min": 6.0, "app_fee_usd": 0, "tuition_cny_yr": 90000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.nottingham.edu.cn/en",
        "url_portal": "https://www.nottingham.edu.cn/en/admissions",
        "coordinates": {"lat": 29.8750, "lng": 121.5501},
        "notes_public": "Nottingham degree. Beautiful campus. Finance, CS, Engineering.",
    },
    # ── 211 Universities ──────────────────────────────────────────────────
    {
        "slug": "bnu", "name": "Beijing Normal University", "name_cn": "北京师范大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 4,
        "league": "211", "diploma_type": "Chinese", "english_ug": "partial",
        "qs_rank": 278, "the_rank": 251, "intl_pct": 10,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 24000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://english.bnu.edu.cn",
        "url_portal": "https://cie.bnu.edu.cn",
        "coordinates": {"lat": 39.9596, "lng": 116.3656},
        "notes_public": "Top for education, psychology, Chinese language.",
    },
    {
        "slug": "ruc", "name": "Renmin University of China", "name_cn": "中国人民大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "partial",
        "qs_rank": 431, "the_rank": 501, "intl_pct": 9,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 25000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.ruc.edu.cn/en",
        "url_portal": "https://iso.ruc.edu.cn",
        "coordinates": {"lat": 39.9629, "lng": 116.3183},
        "notes_public": "Top for economics, law, finance, journalism in China.",
    },
    {
        "slug": "bjtu", "name": "Beijing Jiaotong University", "name_cn": "北京交通大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 701, "the_rank": 601, "intl_pct": 11,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.bjtu.edu.cn/en",
        "url_portal": "https://sie.bjtu.edu.cn",
        "coordinates": {"lat": 39.9541, "lng": 116.3512},
        "notes_public": "Transportation, information tech. Lots of English programs.",
    },
    {
        "slug": "cueb", "name": "Central University of Finance and Economics", "name_cn": "中央财经大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 8,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 23000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.cufe.edu.cn",
        "url_portal": "https://cie.cufe.edu.cn",
        "coordinates": {"lat": 40.0025, "lng": 116.3451},
        "notes_public": "Top finance/economics university. Strong career placement.",
    },
    {
        "slug": "uibe", "name": "University of International Business and Economics", "name_cn": "对外经济贸易大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 15,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 24000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.uibe.edu.cn/en",
        "url_portal": "https://isa.uibe.edu.cn",
        "coordinates": {"lat": 39.9994, "lng": 116.4645},
        "notes_public": "Top for international trade, law, finance. Many English programs.",
    },
    {
        "slug": "bfsu", "name": "Beijing Foreign Studies University", "name_cn": "北京外国语大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 10,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.bfsu.edu.cn/en",
        "url_portal": "https://www.bfsu.edu.cn/en/admissions",
        "coordinates": {"lat": 39.9615, "lng": 116.3018},
        "notes_public": "Top for languages, diplomacy, international affairs.",
    },
    {
        "slug": "cupl", "name": "China University of Political Science and Law", "name_cn": "中国政法大学",
        "city": "Beijing", "province": "Beijing", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 7,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 21000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.cupl.edu.cn",
        "url_portal": "https://isa.cupl.edu.cn",
        "coordinates": {"lat": 40.0110, "lng": 116.2940},
        "notes_public": "China's top law school. LLB in English available.",
    },
    {
        "slug": "swufe", "name": "Southwestern University of Finance and Economics", "name_cn": "西南财经大学",
        "city": "Chengdu", "province": "Sichuan", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 10,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 20000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.swufe.edu.cn",
        "url_portal": "https://isa.swufe.edu.cn",
        "coordinates": {"lat": 30.7215, "lng": 104.0440},
        "notes_public": "Top finance/economics school in western China. Affordable.",
    },
    {
        "slug": "scut", "name": "South China University of Technology", "name_cn": "华南理工大学",
        "city": "Guangzhou", "province": "Guangdong", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 275, "the_rank": 301, "intl_pct": 9,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 24000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.scut.edu.cn/en",
        "url_portal": "https://sie.scut.edu.cn",
        "coordinates": {"lat": 23.0479, "lng": 113.4044},
        "notes_public": "Strong in materials, architecture, light industry. Near HK.",
    },
    {
        "slug": "nwpu", "name": "Northwestern Polytechnical University", "name_cn": "西北工业大学",
        "city": "Xi'an", "province": "Shaanxi", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 401, "the_rank": 501, "intl_pct": 10,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 26000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://en.nwpu.edu.cn",
        "url_portal": "https://sie.nwpu.edu.cn",
        "coordinates": {"lat": 34.2425, "lng": 108.9108},
        "notes_public": "Aerospace, marine, materials. Good scholarships for CIS students.",
    },
    {
        "slug": "jlu", "name": "Jilin University", "name_cn": "吉林大学",
        "city": "Changchun", "province": "Jilin", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 401, "the_rank": 401, "intl_pct": 10,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 21000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www.jlu.edu.cn/en",
        "url_portal": "https://sie.jlu.edu.cn",
        "coordinates": {"lat": 43.8212, "lng": 125.3232},
        "notes_public": "Near Korea/Russia border. Automotive, chemistry, archaeology.",
    },
    {
        "slug": "sxu", "name": "Sichuan University", "name_cn": "四川大学",
        "city": "Chengdu", "province": "Sichuan", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 451, "the_rank": 401, "intl_pct": 8,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://en.scu.edu.cn",
        "url_portal": "https://international.scu.edu.cn",
        "coordinates": {"lat": 30.6312, "lng": 104.0833},
        "notes_public": "Pandas + Chengdu spicy food! Strong in medicine, chemistry.",
    },
    {
        "slug": "hnu", "name": "Hunan University", "name_cn": "湖南大学",
        "city": "Changsha", "province": "Hunan", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 601, "the_rank": 801, "intl_pct": 7,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://www-en.hnu.edu.cn",
        "url_portal": "https://iso.hnu.edu.cn",
        "coordinates": {"lat": 28.1770, "lng": 112.9338},
        "notes_public": "Historic Yuelu Academy campus. Finance, law, engineering.",
    },
    {
        "slug": "ncu", "name": "Nanchang University", "name_cn": "南昌大学",
        "city": "Nanchang", "province": "Jiangxi", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 5,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 18000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://english.ncu.edu.cn",
        "url_portal": "https://international.ncu.edu.cn",
        "coordinates": {"lat": 28.6826, "lng": 115.8931},
        "notes_public": "Affordable option. Food science, materials science standouts.",
    },
    {
        "slug": "cjlu", "name": "China Jiliang University", "name_cn": "中国计量大学",
        "city": "Hangzhou", "province": "Zhejiang", "prestige_stars": 2,
        "league": "Private", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 12,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 16000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.cjlu.edu.cn/en",
        "url_portal": "https://iso.cjlu.edu.cn",
        "coordinates": {"lat": 30.2973, "lng": 120.1024},
        "notes_public": "Hangzhou near Alibaba. Metrology, quality management, engineering.",
    },
    {
        "slug": "hebut", "name": "Hebei University of Technology", "name_cn": "河北工业大学",
        "city": "Tianjin", "province": "Tianjin", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 8,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 18000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.hebut.edu.cn",
        "url_portal": "https://sie.hebut.edu.cn",
        "coordinates": {"lat": 39.1439, "lng": 117.1519},
        "notes_public": "Tianjin campus (close to Beijing). Engineering-focused.",
    },
    {
        "slug": "gxu", "name": "Guangxi University", "name_cn": "广西大学",
        "city": "Nanning", "province": "Guangxi", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 8,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 16000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.gxu.edu.cn",
        "url_portal": "https://iso.gxu.edu.cn",
        "coordinates": {"lat": 22.8411, "lng": 108.2810},
        "notes_public": "ASEAN gateway. Near Vietnam. Agriculture, civil engineering.",
    },
    {
        "slug": "ynu", "name": "Yunnan University", "name_cn": "云南大学",
        "city": "Kunming", "province": "Yunnan", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 12,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 15000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.ynu.edu.cn/en",
        "url_portal": "https://iso.ynu.edu.cn",
        "coordinates": {"lat": 25.0490, "lng": 102.7089},
        "notes_public": "Beautiful Kunming. Biodiversity research, SE Asian studies.",
    },
    {
        "slug": "xmu", "name": "Xiamen University", "name_cn": "厦门大学",
        "city": "Xiamen", "province": "Fujian", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 321, "the_rank": 351, "intl_pct": 9,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 26000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://en.xmu.edu.cn",
        "url_portal": "https://iso.xmu.edu.cn",
        "coordinates": {"lat": 24.4436, "lng": 118.0938},
        "notes_public": "Most beautiful campus in China. By the sea. Finance, chemistry.",
    },
    {
        "slug": "nudt", "name": "National University of Defense Technology", "name_cn": "国防科技大学",
        "city": "Changsha", "province": "Hunan", "prestige_stars": 5,
        "league": "985", "diploma_type": "Chinese", "english_ug": "no",
        "qs_rank": 601, "the_rank": 601, "intl_pct": 3,
        "ielts_min": None, "app_fee_usd": 0, "tuition_cny_yr": 0,
        "portal_status": "CLOSED", "tier": "REACH",
        "url_info": "https://www.nudt.edu.cn",
        "url_portal": None,
        "coordinates": {"lat": 28.1889, "lng": 112.9391},
        "notes_public": "Military university. Very few international students. Requires government nomination.",
    },
    {
        "slug": "ecnu", "name": "East China Normal University", "name_cn": "华东师范大学",
        "city": "Shanghai", "province": "Shanghai", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 451, "the_rank": 601, "intl_pct": 12,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 28000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://english.ecnu.edu.cn",
        "url_portal": "https://admission.ecnu.edu.cn",
        "coordinates": {"lat": 31.2253, "lng": 121.4192},
        "notes_public": "Shanghai. Good for education, psychology, geography.",
    },
    {
        "slug": "scnu", "name": "South China Normal University", "name_cn": "华南师范大学",
        "city": "Guangzhou", "province": "Guangdong", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 7,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 20000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://english.scnu.edu.cn",
        "url_portal": "https://iso.scnu.edu.cn",
        "coordinates": {"lat": 23.1364, "lng": 113.3594},
        "notes_public": "Education, psychology, sports science. Near HK.",
    },
    {
        "slug": "nenu", "name": "Northeast Normal University", "name_cn": "东北师范大学",
        "city": "Changchun", "province": "Jilin", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 8,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 18000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://english.nenu.edu.cn",
        "url_portal": "https://sie.nenu.edu.cn",
        "coordinates": {"lat": 43.8742, "lng": 125.3466},
        "notes_public": "Known for CSC scholarship acceptance. Teacher education.",
    },
    {
        "slug": "nwu", "name": "Northwest University", "name_cn": "西北大学",
        "city": "Xi'an", "province": "Shaanxi", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 6,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 18000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.nwu.edu.cn/en",
        "url_portal": "https://sie.nwu.edu.cn",
        "coordinates": {"lat": 34.2704, "lng": 108.9442},
        "notes_public": "Strong in geology, archaeology, chemistry. Near Terracotta Army.",
    },
    {
        "slug": "lzu", "name": "Lanzhou University", "name_cn": "兰州大学",
        "city": "Lanzhou", "province": "Gansu", "prestige_stars": 3,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 501, "the_rank": 801, "intl_pct": 7,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 18000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.lzu.edu.cn",
        "url_portal": "https://sie.lzu.edu.cn",
        "coordinates": {"lat": 36.0510, "lng": 103.8564},
        "notes_public": "Silk Road location. Good CSC scholarships. Chemistry, ecology.",
    },
    {
        "slug": "xju", "name": "Xinjiang University", "name_cn": "新疆大学",
        "city": "Urumqi", "province": "Xinjiang", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 8,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 15000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.xju.edu.cn/en",
        "url_portal": "https://sie.xju.edu.cn",
        "coordinates": {"lat": 43.8208, "lng": 87.6145},
        "notes_public": "Closest to Kazakhstan. Kazakh/Russian speakers common.",
    },
    {
        "slug": "nmu", "name": "Ningxia University", "name_cn": "宁夏大学",
        "city": "Yinchuan", "province": "Ningxia", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 6,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 14000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.nxu.edu.cn",
        "url_portal": "https://sie.nxu.edu.cn",
        "coordinates": {"lat": 38.4745, "lng": 106.0420},
        "notes_public": "Islamic culture hub. Agricultural, ecology. Affordable.",
    },
    {
        "slug": "imnu", "name": "Inner Mongolia University", "name_cn": "内蒙古大学",
        "city": "Hohhot", "province": "Inner Mongolia", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 5,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 14000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.imu.edu.cn/en",
        "url_portal": "https://sie.imu.edu.cn",
        "coordinates": {"lat": 40.8137, "lng": 111.6536},
        "notes_public": "Near Mongolia and Russia. Mongolian studies, ecology.",
    },
    {
        "slug": "gzu", "name": "Guizhou University", "name_cn": "贵州大学",
        "city": "Guiyang", "province": "Guizhou", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 4,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 15000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.gzu.edu.cn",
        "url_portal": "https://iso.gzu.edu.cn",
        "coordinates": {"lat": 26.4413, "lng": 106.6283},
        "notes_public": "Emerging tech hub. Big data valley of China. Very affordable.",
    },
    {
        "slug": "hfut", "name": "Hefei University of Technology", "name_cn": "合肥工业大学",
        "city": "Hefei", "province": "Anhui", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 7,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 20000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.hfut.edu.cn/en",
        "url_portal": "https://sie.hfut.edu.cn",
        "coordinates": {"lat": 31.8674, "lng": 117.2721},
        "notes_public": "Strong engineering. Near USTC. Automotive industry ties.",
    },
    {
        "slug": "cqu", "name": "Chongqing University", "name_cn": "重庆大学",
        "city": "Chongqing", "province": "Chongqing", "prestige_stars": 4,
        "league": "985", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": 401, "the_rank": 601, "intl_pct": 8,
        "ielts_min": 5.5, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "TARGET",
        "url_info": "https://english.cqu.edu.cn",
        "url_portal": "https://sie.cqu.edu.cn",
        "coordinates": {"lat": 29.5735, "lng": 106.5024},
        "notes_public": "Mountain city. Strong in architecture, energy, mechanical eng.",
    },
    {
        "slug": "heu", "name": "Harbin Engineering University", "name_cn": "哈尔滨工程大学",
        "city": "Harbin", "province": "Heilongjiang", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 12,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://english.hrbeu.edu.cn",
        "url_portal": "https://sie.hrbeu.edu.cn",
        "coordinates": {"lat": 45.7934, "lng": 126.6615},
        "notes_public": "Nuclear engineering, naval architecture, ocean engineering. Russian-friendly.",
    },
    {
        "slug": "nust", "name": "Nanjing University of Science and Technology", "name_cn": "南京理工大学",
        "city": "Nanjing", "province": "Jiangsu", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 10,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 24000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://english.njust.edu.cn",
        "url_portal": "https://sie.njust.edu.cn",
        "coordinates": {"lat": 32.0835, "lng": 118.8277},
        "notes_public": "Defense-related engineering. Materials, automation, CS.",
    },
    {
        "slug": "nuaa", "name": "Nanjing University of Aeronautics and Astronautics", "name_cn": "南京航空航天大学",
        "city": "Nanjing", "province": "Jiangsu", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 9,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 24000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://english.nuaa.edu.cn",
        "url_portal": "https://sie.nuaa.edu.cn",
        "coordinates": {"lat": 31.9680, "lng": 118.8445},
        "notes_public": "Aviation focused. Good CSC scholarships. Popular with CIS students.",
    },
    {
        "slug": "just", "name": "Jiangsu University of Science and Technology", "name_cn": "江苏科技大学",
        "city": "Zhenjiang", "province": "Jiangsu", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 8,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 18000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.just.edu.cn",
        "url_portal": "https://sie.just.edu.cn",
        "coordinates": {"lat": 32.2136, "lng": 119.4495},
        "notes_public": "Shipbuilding, marine. Near Shanghai. CSC scholarships available.",
    },
    {
        "slug": "swu", "name": "Southwest University", "name_cn": "西南大学",
        "city": "Chongqing", "province": "Chongqing", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 8,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 18000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://international.swu.edu.cn",
        "url_portal": "https://sie.swu.edu.cn",
        "coordinates": {"lat": 29.8173, "lng": 106.3945},
        "notes_public": "Huge campus in Chongqing. Agriculture, psychology, education.",
    },
    {
        "slug": "shnu", "name": "Shanghai Normal University", "name_cn": "上海师范大学",
        "city": "Shanghai", "province": "Shanghai", "prestige_stars": 2,
        "league": "Private", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 10,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.shnu.edu.cn/english",
        "url_portal": "https://iso.shnu.edu.cn",
        "coordinates": {"lat": 31.1478, "lng": 121.4136},
        "notes_public": "Shanghai address. Education, arts. Reasonable cost.",
    },
    {
        "slug": "bhu", "name": "Bohai University", "name_cn": "渤海大学",
        "city": "Jinzhou", "province": "Liaoning", "prestige_stars": 1,
        "league": "Private", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 5,
        "ielts_min": 4.0, "app_fee_usd": 0, "tuition_cny_yr": 14000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.bhu.edu.cn",
        "url_portal": "https://iso.bhu.edu.cn",
        "coordinates": {"lat": 41.1236, "lng": 121.1320},
        "notes_public": "Very affordable. Accepts students with lower academic backgrounds.",
    },
    {
        "slug": "whut", "name": "Wuhan University of Technology", "name_cn": "武汉理工大学",
        "city": "Wuhan", "province": "Hubei", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 9,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 21000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.whut.edu.cn",
        "url_portal": "https://sie.whut.edu.cn",
        "coordinates": {"lat": 30.5097, "lng": 114.3570},
        "notes_public": "Materials, transportation, shipbuilding. Large intl student body.",
    },
    {
        "slug": "swjtu", "name": "Southwest Jiaotong University", "name_cn": "西南交通大学",
        "city": "Chengdu", "province": "Sichuan", "prestige_stars": 3,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 9,
        "ielts_min": 5.0, "app_fee_usd": 0, "tuition_cny_yr": 22000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.swjtu.edu.cn/en",
        "url_portal": "https://sie.swjtu.edu.cn",
        "coordinates": {"lat": 30.6441, "lng": 104.0421},
        "notes_public": "High-speed rail capital. Train/transportation engineering.",
    },
    {
        "slug": "qhnu", "name": "Qinghai Normal University", "name_cn": "青海师范大学",
        "city": "Xining", "province": "Qinghai", "prestige_stars": 1,
        "league": "Private", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 5,
        "ielts_min": 4.0, "app_fee_usd": 0, "tuition_cny_yr": 12000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://www.qhnu.edu.cn",
        "url_portal": "https://sie.qhnu.edu.cn",
        "coordinates": {"lat": 36.6235, "lng": 101.7836},
        "notes_public": "Gateway to Tibet plateau. Very affordable. Nature + adventure.",
    },
    {
        "slug": "tyut", "name": "Taiyuan University of Technology", "name_cn": "太原理工大学",
        "city": "Taiyuan", "province": "Shanxi", "prestige_stars": 2,
        "league": "211", "diploma_type": "Chinese", "english_ug": "yes",
        "qs_rank": None, "the_rank": None, "intl_pct": 6,
        "ielts_min": 4.5, "app_fee_usd": 0, "tuition_cny_yr": 16000,
        "portal_status": "OPEN", "tier": "LIKELY",
        "url_info": "https://en.tyut.edu.cn",
        "url_portal": "https://sie.tyut.edu.cn",
        "coordinates": {"lat": 37.8706, "lng": 112.5493},
        "notes_public": "Energy, mining, coal chemistry. Shanxi industrial center.",
    },
]

# Sample majors for top universities
SAMPLE_MAJORS = {
    "sjtu": [
        {"major_name": "Computer Science and Technology", "field": "CS", "language": "English", "duration": "4 years",
         "department": "School of Electronic Information and Electrical Engineering"},
        {"major_name": "Intelligent Science and Technology", "field": "AI", "language": "English", "duration": "4 years",
         "department": "School of Electronic Information and Electrical Engineering"},
        {"major_name": "Electrical Engineering", "field": "EE", "language": "English", "duration": "4 years",
         "department": "School of Electronic Information and Electrical Engineering"},
        {"major_name": "Business Administration", "field": "Business", "language": "English", "duration": "4 years",
         "department": "Antai College of Economics and Management"},
        {"major_name": "Finance", "field": "Finance", "language": "English", "duration": "4 years",
         "department": "Antai College of Economics and Management"},
        {"major_name": "Mechanical Engineering", "field": "ME", "language": "English", "duration": "4 years",
         "department": "School of Mechanical Engineering"},
    ],
    "fudan": [
        {"major_name": "Software Engineering", "field": "CS", "language": "English", "duration": "4 years",
         "department": "School of Computer Science"},
        {"major_name": "International Economics and Trade", "field": "Economics", "language": "English", "duration": "4 years",
         "department": "School of Economics"},
        {"major_name": "Chinese Language and Literature", "field": "Humanities", "language": "Chinese", "duration": "4 years",
         "department": "School of Chinese Language and Literature"},
    ],
    "nyu-shanghai": [
        {"major_name": "Computer Science", "field": "CS", "language": "English", "duration": "4 years",
         "department": "Division of Science"},
        {"major_name": "Business and Finance", "field": "Finance", "language": "English", "duration": "4 years",
         "department": "Division of Social Science"},
        {"major_name": "Data Science", "field": "Data Science", "language": "English", "duration": "4 years",
         "department": "Division of Science"},
        {"major_name": "Neural Science", "field": "Life Sciences", "language": "English", "duration": "4 years",
         "department": "Division of Science"},
        {"major_name": "Interactive Media Arts", "field": "Arts", "language": "English", "duration": "4 years",
         "department": "Arts and Humanities"},
    ],
    "cuhk-sz": [
        {"major_name": "Computer Science and Engineering", "field": "CS", "language": "English", "duration": "4 years",
         "department": "School of Science and Engineering"},
        {"major_name": "Financial Mathematics", "field": "Finance", "language": "English", "duration": "4 years",
         "department": "School of Science and Engineering"},
        {"major_name": "Business Administration", "field": "Business", "language": "English", "duration": "4 years",
         "department": "School of Management and Economics"},
        {"major_name": "Humanities and Social Science", "field": "Humanities", "language": "English", "duration": "4 years",
         "department": "School of Humanities and Social Science"},
    ],
    "xjtlu": [
        {"major_name": "Computer Science and Technology", "field": "CS", "language": "English", "duration": "4 years",
         "department": "School of Advanced Technology"},
        {"major_name": "Financial Mathematics", "field": "Finance", "language": "English", "duration": "4 years",
         "department": "School of Mathematics and Physics"},
        {"major_name": "Architecture", "field": "Architecture", "language": "English", "duration": "5 years",
         "department": "School of Design"},
        {"major_name": "Artificial Intelligence", "field": "AI", "language": "English", "duration": "4 years",
         "department": "School of Advanced Technology"},
    ],
}

# Sample scholarships
SAMPLE_SCHOLARSHIPS = [
    {
        "university_id": None,  # national
        "name": "Chinese Government Scholarship (CSC)",
        "type": "full",
        "coverage": "Tuition + accommodation + living allowance + insurance",
        "amount_cny_yr": 36000,
        "conditions": "Must maintain GPA ≥3.0. Apply through home country embassy.",
        "url": "https://www.campuschina.org",
        "renewable": True,
        "notes": "Full scholarship covering everything. Most prestigious for internationals.",
    },
    {
        "university_id": None,
        "name": "Beijing Municipal Government Scholarship",
        "type": "full",
        "coverage": "Tuition + accommodation",
        "amount_cny_yr": 28000,
        "conditions": "Must study in Beijing university. Applied via university.",
        "renewable": True,
        "notes": "For universities in Beijing. Very competitive.",
    },
    {
        "university_id": None,
        "name": "Shanghai Government Scholarship",
        "type": "partial",
        "coverage": "Partial tuition waiver",
        "amount_cny_yr": 15000,
        "conditions": "Must study in Shanghai university.",
        "renewable": True,
        "notes": "For Shanghai universities. Easier to get than CSC.",
    },
    {
        "university_id": None,
        "name": "Silk Road Scholarship",
        "type": "full",
        "coverage": "Tuition + accommodation + stipend",
        "amount_cny_yr": 30000,
        "conditions": "For students from Belt & Road countries (Kazakhstan, Uzbekistan, etc.)",
        "renewable": True,
        "notes": "Specifically designed for Central Asian students!",
    },
]


def seed():
    db = SessionLocal()
    try:
        # Check if already seeded
        if db.query(University).count() > 0:
            print(f"Already seeded: {db.query(University).count()} universities")
            return

        print("Seeding universities...")
        uni_map = {}
        for uni_data in UNIVERSITIES:
            uni = University(**uni_data)
            db.add(uni)
            db.flush()
            uni_map[uni.slug] = uni

        db.commit()
        print(f"Added {len(UNIVERSITIES)} universities")

        # Seed majors
        print("Seeding majors...")
        for slug, majors_data in SAMPLE_MAJORS.items():
            if slug in uni_map:
                for m_data in majors_data:
                    m = Major(university_id=uni_map[slug].id, **m_data)
                    db.add(m)
        db.commit()

        # Seed national scholarships
        print("Seeding scholarships...")
        for s_data in SAMPLE_SCHOLARSHIPS:
            s = Scholarship(**s_data)
            db.add(s)
        db.commit()

        # Seed some deadlines
        print("Seeding deadlines...")
        for slug in ["sjtu", "fudan", "pku", "thu", "zju", "nyu-shanghai", "cuhk-sz"]:
            if slug in uni_map:
                uni = uni_map[slug]
                db.add(Deadline(
                    university_id=uni.id, round_label="R1",
                    deadline_date=date(2025, 1, 15), result_date=date(2025, 3, 1),
                    scholarship_eligible=True
                ))
                db.add(Deadline(
                    university_id=uni.id, round_label="R2",
                    deadline_date=date(2025, 3, 15), result_date=date(2025, 5, 1),
                    scholarship_eligible=True
                ))
                db.add(Deadline(
                    university_id=uni.id, round_label="Final",
                    deadline_date=date(2025, 5, 31), result_date=date(2025, 7, 1),
                    scholarship_eligible=False
                ))
        db.commit()

        print("✓ Seed complete!")
        print(f"  Universities: {db.query(University).count()}")
        print(f"  Majors: {db.query(Major).count()}")
        print(f"  Scholarships: {db.query(Scholarship).count()}")
        print(f"  Deadlines: {db.query(Deadline).count()}")

    finally:
        db.close()


if __name__ == "__main__":
    seed()
